[tox]
envlist = py
isolated_build = true

[testenv]
skip_missing_interpreters = true
setenv =
    PYTHONIOENCODING = utf-8
passenv = 
    TEST_URL
    TEST_SLACK_URL
    TEST_WEBEX_URL
deps =
    pytest
    toml
    requests
commands =
    pytest -s