name: Run Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  TEST_URL: ${{secrets.TEST_URL}}

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Tox
        run: pip install tox

      - name: Run tests
        run: |
          printenv | cut -d= -f1
          echo ${TEST_URL:0:5}
          tox
        