name: Run Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  TEST_URL: ${{secrets.TEST_URL}}
  TEST_SLACK_URL: ${{secrets.TEST_SLACK_URL}}
  TEST_WEBEX_URL: ${{secrets.TEST_WEBEX_URL}}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Tox
        run: pip install tox

      - name: Run tests
        run: tox
        
